SELECT T.VEHICLETYPE_NAME, MAKE.VEHICLEMAKE_NAME, MODELS.VEHICLEMODEL_NAME 
FROM VEHICLE_MAKEMODEL_MAPPING MMM LEFT JOIN VEHICLETYPE T
ON MMM.VT_ID = T.VT_ID
LEFT JOIN VEHICLE_MAKE MAKE 
ON MMM.VMAKE_ID = MAKE.VMAKE_ID
LEFT JOIN VEHICLE_MODEL MODELS 
ON MMM.VMODEL_ID = MODELS.VMODEL_ID
WHERE MMM.VT_ID = 1;



SELECT MMM.VMMP_ID, T.VEHICLETYPE_NAME, MAKE.VEHICLEMAKE_NAME, 
MODELS.VEHICLEMODEL_NAME, RP.VPM_ID VPM, RP.VALUE
FROM VEHICLE_RECORDS VR, VEHICLE_MAKEMODEL_MAPPING MMM, VEHICLETYPE T, 
VEHICLE_MAKE MAKE, VEHICLE_MODEL MODELS, VEHICLE_RECORDS R,VEHICLE_RECORDS_PROPERTIES RP  
WHERE VR.VMMP_ID = MMM.VMMP_ID
AND MMM.VT_ID = T.VT_ID
AND MMM.VMAKE_ID = MAKE.VMAKE_ID
AND MMM.VMODEL_ID = MODELS.VMODEL_ID
AND R.VR_ID = RP.VR_ID
AND R.VR_ID = 1
AND MMM.VT_ID = 1;


SELECT RP.VPM_ID VPM, RP.VALUE FROM VEHICLE_RECORDS R, VEHICLE_RECORDS_PROPERTIES RP
WHERE R.VR_ID = RP.VR_ID
AND R.VR_ID = 1;

CREATE TABLE [dbo].[VEHICLE](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[TYPE] [nvarchar](200) NOT NULL,
	[MAKE] [nvarchar](200) NOT NULL,
	[MODEL] [nvarchar](200) NOT NULL,
	[ENGINE] [nvarchar](200) NOT NULL,
	[WHEELS] [nvarchar](200) NOT NULL,
	[DOORS] [nvarchar](200) NOT NULL,
	[BODYTYPE] [nvarchar](200) NOT NULL,
	[COLOURS] [nvarchar](200) NOT NULL,
	[IS_ACTIVE] [char](10) NULL,
	[CREATED_BY] [nvarchar](200) NULL,
	[CREATED_DATE] [date] NULL,
	[MODIFIED_BY] [nvarchar](200) NULL,
	[MODIFIED_DATE] [date] NULL,
	[DESCRIPTION] [nvarchar](100) NULL)