USE [Vehicles]
GO

/****** Object:  Table [dbo].[VEHICLE_MAKEMODEL_MAPPING]    Script Date: 9/04/2019 3:52:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VEHICLE_MAKEMODEL_MAPPING](
	[VMMP_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[VT_ID] [numeric](18, 0) NOT NULL,
	[VMAKE_ID] [numeric](18, 0) NOT NULL,
	[VMODEL_ID] [numeric](18, 0) NOT NULL,
	[IS_ACTIVE] [char](10) NULL,
	[CREATED_BY] [nvarchar](200) NULL,
	[CREATED_DATE] [date] NULL,
	[MODIFIED_BY] [nvarchar](200) NULL,
	[MODIFIED_DATE] [date] NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
 CONSTRAINT [PK_VEHICLE_MAKEMODEL_MAPPING] PRIMARY KEY CLUSTERED 
(
	[VMMP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VEHICLE_MAKEMODEL_MAPPING]  WITH CHECK ADD FOREIGN KEY([VMAKE_ID])
REFERENCES [dbo].[VEHICLE_MAKE] ([VMAKE_ID])
GO

ALTER TABLE [dbo].[VEHICLE_MAKEMODEL_MAPPING]  WITH CHECK ADD FOREIGN KEY([VMODEL_ID])
REFERENCES [dbo].[VEHICLE_MODEL] ([VMODEL_ID])
GO

ALTER TABLE [dbo].[VEHICLE_MAKEMODEL_MAPPING]  WITH CHECK ADD FOREIGN KEY([VT_ID])
REFERENCES [dbo].[VEHICLETYPE] ([VT_ID])
GO


