USE [Vehicles]
GO

/****** Object:  Table [dbo].[VEHICLE_RECORDS]    Script Date: 9/04/2019 3:53:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VEHICLE_RECORDS](
	[VR_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[VMMP_ID] [numeric](18, 0) NOT NULL,
	[IS_ACTIVE] [char](10) NULL,
	[CREATED_BY] [nvarchar](200) NULL,
	[CREATED_DATE] [date] NULL,
	[MODIFIED_BY] [nvarchar](200) NULL,
	[MODIFIED_DATE] [date] NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
 CONSTRAINT [PK_VEHICLE_RECORDS] PRIMARY KEY CLUSTERED 
(
	[VR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VEHICLE_RECORDS]  WITH CHECK ADD FOREIGN KEY([VMMP_ID])
REFERENCES [dbo].[VEHICLE_MAKEMODEL_MAPPING] ([VMMP_ID])
GO


