USE [Vehicles]
GO

/****** Object:  Table [dbo].[VEHICLE_RECORDS_PROPERTIES]    Script Date: 9/04/2019 3:54:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VEHICLE_RECORDS_PROPERTIES](
	[VRP_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[VR_ID] [numeric](18, 0) NOT NULL,
	[VPM_ID] [numeric](18, 0) NOT NULL,
	[VALUE] [nvarchar](200) NOT NULL,
	[IS_ACTIVE] [char](10) NULL,
	[CREATED_BY] [nvarchar](200) NULL,
	[CREATED_DATE] [date] NULL,
	[MODIFIED_BY] [nvarchar](200) NULL,
	[MODIFIED_DATE] [date] NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
 CONSTRAINT [PK_VEHICLE_RECORDS_PROPERTIES] PRIMARY KEY CLUSTERED 
(
	[VRP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VEHICLE_RECORDS_PROPERTIES]  WITH CHECK ADD FOREIGN KEY([VPM_ID])
REFERENCES [dbo].[VEHICLE_PROPERTIES_MAPPING] ([VPM_ID])
GO

ALTER TABLE [dbo].[VEHICLE_RECORDS_PROPERTIES]  WITH CHECK ADD FOREIGN KEY([VR_ID])
REFERENCES [dbo].[VEHICLE_RECORDS] ([VR_ID])
GO


